baseURL = "https://damuwangs.github.io"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "DaMuWang"
# copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # 代码高亮style 参考：https://xyproto.github.io/splash/docs/all.html
    style = "friendly"
    tabWidth = 4

[params]
subtitle = "damuwang's blog"
# 关闭评论
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/posts"
name = "博客"
weight = 1
# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 4
